using DFMS.Shared.Extensions;
using System.IO;
using System.Security.Claims;

namespace DFMS.WebApi.Authorization
{
    public class CustomClaim : Claim
    {
        public CustomClaim(UserClaim claim, string value) : this(claim.ToCamelCase(), value) { }

        #region AutoGenerated
        public CustomClaim(BinaryReader reader) : base(reader) { }
        public CustomClaim(BinaryReader reader, ClaimsIdentity subject) : base(reader, subject) { }
        public CustomClaim(string type, string value) : base(type, value) { }
        public CustomClaim(string type, string value, string valueType) : base(type, value, valueType) { }
        public CustomClaim(string type, string value, string valueType, string issuer) : base(type, value, valueType, issuer) { }
        public CustomClaim(string type, string value, string valueType, string issuer, string originalIssuer) : base(type, value, valueType, issuer, originalIssuer) { }
        public CustomClaim(string type, string value, string valueType, string issuer, string originalIssuer, ClaimsIdentity subject) : base(type, value, valueType, issuer, originalIssuer, subject) { }
        protected CustomClaim(Claim other) : base(other) { }
        protected CustomClaim(Claim other, ClaimsIdentity subject) : base(other, subject) { }
        #endregion
    }
}
